.\" Copyright (c) 2006
.\"	A. Maitland Bottoms
.\"
.Dd November 28, 2006
.Dt COOLKEY 1
.Os Debian
.Sh NAME
.Nm coolkey-pk11install
.Nd Add Coolkey to Mozilla NSS
.Sh SYNOPSIS
.Nm coolkey-pk11install
.Op Fl i
.Op Fl u
.Op Fl v
.Op Fl p
.Ar PATH
.Pp
Options are (i, install) (u, uninstall) (v, verbose) (p, path)
.Sh INTRODUCTION
.Nm coolkey-pk11install
Handles placing the coolkey loadable modules in the right place for
integration with web browsers and mail user agents that use
Mozilla NSS.
.Pp
"pk11install is really a generic tool that probably should be moved to
NSS (you can change the parameters and install any PKCS #11
module)." ... "It differs form modutil in that it doesn't try
to load the module itself to install it. It also differs from modutil
in that it 'knows' where several NSS apps store their database (OK,
where old netscape and modern mozilla apps). You can run it as a user
and install your favorite PKCS #11 module into all the
browsers/mailreaders you have installed."
 - Bob Relyea, a coolkey developer.
.Pp
.Sh SUMMARY
(Good luck)
.Pp
.Sh FILES
None.
It is up to the user to keep track of state when necessary.
.Pp
.Sh SEE ALSO
.Xr mozilla 1 ,
.Sh HISTORY
An LGPL licensed security module to allow Smart Card use.
.Pp
.Sh BUGS
Maybe too many.
.Pp
.\" This bug is no longer:
.\" No man page.
